In [2]:
import pandas as pd

PMD_CSV_FILE=r'report.csv'

In [5]:
coverage = pd.read_csv(PMD_CSV_FILE)
prioritized = coverage.sort_values(by=["Priority"], ascending=True)

prioritized.head()

,Problem,Package,File,Priority,Line,Description,Rule set,Rule
8,1,org.flower.productapi,/Users/anthonyikeda/work/git/product-api/src/m...,1,23,The method parameter name '_service' doesn't m...,Code Style,FormalParameterNamingConventions
9,2,org.flower.productapi,/Users/anthonyikeda/work/git/product-api/src/m...,2,29,Logger calls should be surrounded by log level...,Best Practices,GuardLogStatement
4,1,org.flower.productapi,/Users/anthonyikeda/work/git/product-api/src/m...,2,29,Logger calls should be surrounded by log level...,Best Practices,GuardLogStatement
13,1,org.flower.productapi,/Users/anthonyikeda/work/git/product-api/src/m...,2,54,Logger calls should be surrounded by log level...,Best Practices,GuardLogStatement
10,3,org.flower.productapi,/Users/anthonyikeda/work/git/product-api/src/m...,2,43,Logger calls should be surrounded by log level...,Best Practices,GuardLogStatement

In [9]:
pd.set_option('display.max_colwidth', None)
prioritized_categories = coverage.groupby(["Description", "Priority"])["Description"].count().reset_index(name="count")

prioritized_categories.sort_values(by=["count"], ascending=False).head()
# coverage.groupby(["Description", "Priority"])["Description"].count().reset_index(name="count").sort_values(by=["count"], ascending=False)

,Description,Priority,count
4,Logger calls should be surrounded by log level guards.,2,5
1,Avoid the use of value in annotations when its the only element,3,2
12,Unused import 'javax.persistence.*',4,2
0,"Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block",3,1
2,Avoid unused private methods such as 'convertDAO(ProductRequestDAO)'.,3,1